import { Beaker, FlaskRound, Microscope, Sparkles, type LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

export type ScienceStatus = "measured" | "simulation" | "illustrative" | "experimental";

interface Spec {
  label: string;
  short: string;
  icon: LucideIcon;
  description: string;
  classes: string;
}

const SPECS: Record<ScienceStatus, Spec> = {
  measured: {
    label: "Measured from data",
    short: "Measured",
    icon: Microscope,
    description: "Computed directly from the uploaded or bundled time series — descriptive, not predictive.",
    classes: "bg-emerald-50 border-emerald-200 text-emerald-700",
  },
  simulation: {
    label: "Simulation from declared parameters",
    short: "Simulation",
    icon: Beaker,
    description:
      "Generated by the spin-glass kernel given an explicit coupling matrix, field, temperature and pattern. Valid as simulation, not empirical proof.",
    classes: "bg-blue-50 border-blue-200 text-blue-700",
  },
  illustrative: {
    label: "Illustrative theory",
    short: "Illustrative",
    icon: Sparkles,
    description:
      "Drawn from the underlying mathematical form (tanh, energy potential, pulse window) to convey intuition. Not estimated from data.",
    classes: "bg-amber-50 border-amber-200 text-amber-700",
  },
  experimental: {
    label: "Experimental heuristic",
    short: "Experimental",
    icon: FlaskRound,
    description:
      "Uses an unvalidated heuristic such as signed mutual information. Useful for exploration; do not cite as a peer-reviewed result.",
    classes: "bg-fuchsia-50 border-fuchsia-200 text-fuchsia-700",
  },
};

interface ScienceBadgeProps {
  status: ScienceStatus;
  inline?: boolean;
  showLabel?: boolean;
  className?: string;
}

export function ScienceBadge({ status, inline = false, showLabel = true, className }: ScienceBadgeProps) {
  const spec = SPECS[status];
  const Icon = spec.icon;
  if (inline) {
    return (
      <span
        className={cn(
          "inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-[10.5px] font-medium",
          spec.classes,
          className,
        )}
        title={spec.description}
      >
        <Icon className="h-3 w-3" />
        {showLabel ? spec.short : null}
      </span>
    );
  }
  return (
    <div className={cn("flex items-start gap-2.5 rounded-md border px-3 py-2 text-xs", spec.classes, className)}>
      <Icon className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <div className="space-y-0.5">
        <p className="font-semibold leading-tight">{spec.label}</p>
        <p className="leading-snug opacity-90">{spec.description}</p>
      </div>
    </div>
  );
}
