import { Download, FileText } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { SummaryBox } from "@/components/summary-box";
import { Button } from "@/components/ui/button";

const FIGURES: { src: string; title: string; caption: string }[] = [
  {
    src: "/figures/signed_coupling_heatmap.png",
    title: "Signed coupling heatmap",
    caption: "Which associations reinforce vs which pull against each other in the recovered J.",
  },
  {
    src: "/figures/scenario_metrics.png",
    title: "Scenario metrics",
    caption: "Overlap, frustration, and purchase probability across baseline → moderate → heavy.",
  },
  {
    src: "/figures/pulse_response.png",
    title: "Pulse response",
    caption: "Same field input → either fast buzz that decays, or a residual memory tail.",
  },
  {
    src: "/figures/hysteresis.png",
    title: "Hysteresis",
    caption: "Brand state under increasing vs decreasing pressure is not the same path.",
  },
  {
    src: "/figures/energy_landscape.png",
    title: "Energy landscape",
    caption: "Campaign field tilts the basin; durable impact deepens the target minimum.",
  },
];

export default function ReportsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Output"
        title="Reports"
        description="The full 12-page PDF brief, plus the five reference figures it renders inline."
        actions={
          <Button asChild>
            <a
              href="https://github.com/matiyashu/spinglass-marketing-exploration/raw/main/backend/docs/spin_glass_brand_marketing_report.pdf"
              target="_blank"
              rel="noreferrer"
            >
              <FileText className="h-4 w-4" /> Download PDF
            </a>
          </Button>
        }
      />

      <SummaryBox title="What's in here">
        The PDF brief walks the full framework — Hamiltonian, coupling estimators, memory attractors, non-equilibrium
        dynamics, hysteresis, parameter chaos, applied use cases, and a Python implementation blueprint. The five PNGs
        below are excerpts from it, sized for direct use in decks. When the optional FastAPI service is live, this page
        also regenerates the PDF on uploaded data.
      </SummaryBox>

      <section className="grid gap-4 md:grid-cols-2">
        {FIGURES.map((fig) => (
          <figure key={fig.src} className="overflow-hidden rounded-xl border bg-card shadow-sm">
            <img src={fig.src} alt={fig.title} className="w-full" />
            <figcaption className="space-y-1 border-t p-4">
              <h3 className="text-sm font-semibold">{fig.title}</h3>
              <p className="text-xs text-muted-foreground">{fig.caption}</p>
              <a
                href={fig.src}
                download
                className="inline-flex items-center gap-1 pt-1 text-xs font-medium text-primary hover:underline"
              >
                <Download className="h-3 w-3" /> Download PNG
              </a>
            </figcaption>
          </figure>
        ))}
      </section>

      <SummaryBox tone="info" eyebrow="How to read this">
        The figures are deliberately self-contained: each is captioned with its core takeaway in the PDF. Drop them
        directly into a strategy deck. The PDF itself is generated by{" "}
        <code className="font-mono text-xs">backend/generate_spin_glass_marketing_report.py</code> — re-run it after any
        kernel change to refresh.
      </SummaryBox>
    </>
  );
}
